# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
